# This is a basic workflow to help you get started with Actions

name: MarkdownParse JUnit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: #can be called anything other than build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #specifying OS/computer being runned on 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: #what we're going to be doing
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 #allows access to your code

      # Runs a set of commands using the runners shell
      - name: Compile and run our JUnit tests, also test out echo
        run: |     #what we're going to run  #echo: prints out something on terminal #on every push, runs tests
          echo The directory is: $GITHUB_WORKSPACE 
          javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar MarkdownParseTest.java ActualMarkdown.java
          java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore MarkdownParseTest
